; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=loop-tensorize -S < %s | FileCheck %s

; Verify the pass runs without crashing on a trivial function.
; CHECK-LABEL: define void @trivial
define void @trivial() {
  ret void
}
